### ISSUE TITLE
Kjøre flere heiser

### ISSUE THREAD

**Issue by tobiasny** [mazzus/graphical-elevator-simulator#1]
Yoo :)

Starta simulatoren på port 3001 og det funker smud! Prøvde å skrive '--help elevator-simulator-darwin-amd64' for å finne ut av hvordan jeg mekker flere heiser ved å bytte port, men det funka ikke. Hvordan fikser jeg det? :P

Siiiick simulator

**Comment by mazzus** [comment]
For å få hjelp, kjør:

```bash
elevator-simulator-darwin-amd64 --help
```

For å kjøre flere simulatorer må hver simulator for en egen web-port (den brukes for å kommunisere med nettleseren) og egen client-port (den brukes for å kommunisere emd heis-programmet).

Den første simulatoren kan for eksempel kjøre slik:
```bash
elevator-simulator-darwin-amd64 --client-port 3001 --web-port 15657
```

Og den neste:
```bash
elevator-simulator-darwin-amd64 --client-port 3002 --web-port 15658
```
Du må da passe på at det første heisprogrammet bruker port 15657 for å kommunisere med simulatoren og det andre programmet må bruke port 15658.

Du kan så åpne disse adressene i nettleseren:
<http://localhost:3001> (første simulatoren)
<http://localhost:3003> (andre simulatoren)

Håper dette hjelper!
Bra at du digger simulatoren :+1:
